export const gameModes = {
  GAME_MODE: 'PLAY',
  TRAINING_MODE: 'TRAIN',
};

export const actions = {
  NEXT_QUESTION: 'NEXT_QUESTION',
  START_GAME: 'START_GAME',
  START_TRAIN: 'START_TRAIN',
  FINISH_GAME: 'FINISH_GAME',
  UPDATE_STATISTIC: 'UPDATE_STATISTIC',
  ANSWER: 'ANSWER',
  REFRESH_DECK: 'REFRESH_DECK',
  SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',
  CHANGE_MODE: 'CHANGE_MODE',
  CORRECT_ANSWER: 'CORRECT_ANSWER',
  INCORRECT_ANSWER: 'INCORRECT_ANSWER',
  ABBONDED_GAME: 'ABBONDED_GAME',
  STATISTIC_PLUS_CLICKED: 'STATISTIC_PLUS_CLICKED',
  COMPLICATE_WORD_REPEAT: 'COMPLICATE_WORD_REPEAT',
};
